In [1]:
print("Hello World!")

Hello World!

In [1]:
from dataFetch import clean_data, fetch_player_data, fetch_team_data
from config import MANAGER_ID, GAMEWEEK
player_df, team_df = clean_data()
player_df.head()

,web_name,element_type,team,now_cost,selected_by_percent,total_points,event_points,points_per_game,form,transfers_in_event,...,match_4_eGI,match_4_xPts,match_5_xga,match_5_defScore,match_5_eGI,match_5_xPts,eGI_5,xgA_5,ds_5,xpts_5
0,Raya,GKP,ARS,6.1,42.2,30,1,6.0,6.0,118083,...,0.001203,4.582374,0.938,0.540351,0.001309,4.899198,0.006107,5.644,2.266396,23.450344
1,Arrizabalaga,GKP,ARS,4.9,0.1,0,0,0.0,0.0,95,...,0.000000,2.180208,0.938,0.540351,0.000000,2.496843,0.000000,5.644,2.266396,11.439351
2,Meslier,GKP,ARS,4.9,0.0,0,0,0.0,0.0,44,...,0.000000,2.180208,0.938,0.540351,0.000000,2.496843,0.000000,5.644,2.266396,11.439351
3,Gabriel,DEF,ARS,8.0,22.7,25,1,5.0,5.0,21678,...,0.111745,5.183807,0.938,0.938363,0.121522,5.758306,0.567051,5.644,3.935779,26.874836
4,J.Timber,DEF,ARS,6.5,0.4,1,0,0.5,0.2,11165,...,0.003610,2.158027,0.938,0.479007,0.003926,2.439511,0.018320,5.644,2.009102,11.268010

In [2]:
team_df.head()

,id,short_name,position,played,F1,F2,F3,F4,F5,fdr_sum_next_5,team,xgTeam,xgaTeam
0,1,ARS,2,0,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,ARS,8.51,4.03
1,2,AVL,16,0,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,AVL,4.56,9.22
2,3,BOU,17,0,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,BOU,6.79,6.95
3,4,BRE,4,0,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,BRE,10.21,6.32
4,5,BHA,3,0,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,BHA,11.55,8.67

In [4]:
team_df.columns

Index(['id', 'short_name', 'position', 'played', 'F1', 'F2', 'F3', 'F4', 'F5',
       'fdr_sum_next_5', 'team', 'xgTeam', 'xgaTeam'],
      dtype='str')