In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
from dataFetch import fetch_team_data, fetch_understat, clean_data

In [12]:
u = fetch_team_data()
u.head(10)

,id,short_name,position,F1,F2,F3,F4,F5,fdr_sum_next_5,Team_ID,...,Deep_Passes_Allowed,PPDA_Attacking_Passes,PPDA_Defensive_Actions,PPDA_Allowed_Att,PPDA_Allowed_Def,PPDA_Coeff,PPDA_Allowed_Coeff,Played,xgA/90,xg/90
0,1,ARS,2,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,83,...,23,844,82,1313,103,10.292683,12.747573,5,1.090756,1.882608
1,2,AVL,16,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,71,...,45,1241,72,1080,125,17.236111,8.640000,5,2.171269,0.997899
2,3,BOU,17,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,73,...,42,1163,118,1006,117,9.855932,8.598291,5,1.398999,1.619735
3,4,BRE,4,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,244,...,42,1130,125,944,122,9.040000,7.737705,5,1.499141,2.102884
4,5,BHA,3,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,220,...,39,742,135,1569,70,5.496296,22.414286,5,1.725226,2.578624
5,6,CHE,10,BOU(H) (3),EVE(A) (3),TOT(H) (2),MUN(H) (4),SUN(A) (3),15,80,...,34,1275,92,1004,100,13.858696,10.040000,5,2.059466,1.788420
6,7,COV,18,NEW(H) (3),TOT(A) (3),FUL(H) (2),SUN(H) (3),EVE(A) (3),14,294,...,38,1527,82,897,87,18.621951,10.310345,5,1.717609,0.995119
7,8,CRY,15,NFO(H) (3),BHA(A) (4),NEW(H) (3),TOT(A) (3),LIV(H) (4),17,78,...,56,1597,102,1177,107,15.656863,11.000000,5,2.003992,1.516864
8,9,EVE,7,HUL(A) (2),CHE(H) (4),ARS(A) (5),NEW(A) (3),COV(H) (2),16,72,...,35,1492,98,1075,118,15.224490,9.110169,5,1.439970,1.670814
9,10,FUL,19,IPS(A) (2),HUL(H) (2),COV(A) (2),AVL(A) (3),NEW(H) (3),12,228,...,39,1181,101,1590,96,11.693069,16.562500,5,2.085758,1.592701

In [13]:
p, t = clean_data()

KeyError: 'defensive_contributions'

In [14]:
t.head(20)

,id,short_name,position,F1,F2,F3,F4,F5,fdr_sum_next_5,Team_ID,...,PPDA_Attacking_Passes,PPDA_Defensive_Actions,PPDA_Allowed_Att,PPDA_Allowed_Def,PPDA_Coeff,PPDA_Allowed_Coeff,Played,xgA/90,xg/90,defensive_multiplier
0,1,ARS,2,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,83,...,844,82,1313,103,10.292683,12.747573,5,1.090756,1.882608,0.666140
1,2,AVL,16,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,71,...,1241,72,1080,125,17.236111,8.640000,5,2.171269,0.997899,1.319227
2,3,BOU,17,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,73,...,1163,118,1006,117,9.855932,8.598291,5,1.398999,1.619735,0.962773
3,4,BRE,4,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,244,...,1130,125,944,122,9.040000,7.737705,5,1.499141,2.102884,1.005622
4,5,BHA,3,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,220,...,742,135,1569,70,5.496296,22.414286,5,1.725226,2.578624,1.076349
5,6,CHE,10,BOU(H) (3),EVE(A) (3),TOT(H) (2),MUN(H) (4),SUN(A) (3),15,80,...,1275,92,1004,100,13.858696,10.040000,5,2.059466,1.788420,1.176012
6,7,COV,18,NEW(H) (3),TOT(A) (3),FUL(H) (2),SUN(H) (3),EVE(A) (3),14,294,...,1527,82,897,87,18.621951,10.310345,5,1.717609,0.995119,1.064419
7,8,CRY,15,NFO(H) (3),BHA(A) (4),NEW(H) (3),TOT(A) (3),LIV(H) (4),17,78,...,1597,102,1177,107,15.656863,11.000000,5,2.003992,1.516864,1.343027
8,9,EVE,7,HUL(A) (2),CHE(H) (4),ARS(A) (5),NEW(A) (3),COV(H) (2),16,72,...,1492,98,1075,118,15.224490,9.110169,5,1.439970,1.670814,0.919610
9,10,FUL,19,IPS(A) (2),HUL(H) (2),COV(A) (2),AVL(A) (3),NEW(H) (3),12,228,...,1181,101,1590,96,11.693069,16.562500,5,2.085758,1.592701,1.230615
10,11,HUL,8,EVE(H) (3),FUL(A) (3),BRE(H) (3),IPS(H) (2),ARS(A) (5),16,91,...,1572,94,728,71,16.723404,10.253521,5,1.437056,1.146178,0.944375
11,12,IPS,11,FUL(H) (2),MCI(A) (5),NFO(H) (3),HUL(A) (2),BOU(H) (3),15,285,...,1447,120,1192,106,12.058333,11.245283,5,2.061685,1.424798,1.220315
12,13,LEE,5,ARS(A) (5),MUN(H) (4),SUN(A) (3),BOU(A) (3),TOT(H) (2),17,245,...,1128,117,1036,122,9.641026,8.491803,5,1.282519,1.445193,0.774204
13,14,LIV,6,MCI(H) (4),BRE(A) (3),BHA(H) (3),ARS(H) (4),CRY(A) (3),17,87,...,958,129,1325,94,7.426357,14.095745,5,1.387830,1.648832,0.862618
14,15,MCI,1,LIV(A) (4),IPS(H) (2),AVL(A) (3),BHA(H) (3),NFO(A) (3),15,88,...,922,108,1781,131,8.537037,13.595420,5,1.435448,2.208146,0.848311
15,16,MUN,12,TOT(H) (2),LEE(A) (3),BOU(H) (3),CHE(A) (4),AVL(H) (3),15,89,...,1113,101,1395,95,11.019802,14.684211,5,1.443192,2.117004,0.773590
16,17,NEW,9,COV(A) (2),AVL(H) (3),CRY(A) (3),EVE(H) (3),FUL(A) (3),14,86,...,1082,103,1199,127,10.504854,9.440945,5,1.867938,1.108836,1.059378
17,18,NFO,13,CRY(A) (3),ARS(H) (4),IPS(A) (2),BRE(A) (3),MCI(H) (4),16,249,...,1189,107,940,118,11.112150,7.966102,5,1.002305,1.696155,0.593611
18,19,TOT,20,MUN(A) (4),COV(H) (2),CHE(A) (4),CRY(H) (2),LEE(A) (3),15,82,...,1031,137,1385,114,7.525547,12.149123,5,1.838504,1.163948,1.124819
19,20,SUN,14,BHA(H) (3),BOU(A) (3),LEE(H) (3),COV(A) (2),CHE(H) (4),15,77,...,1130,115,1128,115,9.826087,9.808696,5,1.770404,2.014310,1.034986

In [16]:
p.head(30)

,web_name,element_type,team,now_cost,selected_by_percent,total_points,event_points,points_per_game,form,transfers_in_event,...,opp2,opp3,opp4,opp5,opp_1_score,opp_2_score,opp_3_score,opp_4_score,opp_5_score,5gw_attack_score
0,Raya,GKP,ARS,6.1,42.2,30,1,6.0,6.0,120800,...,NFO,EVE,LIV,HUL,0.013370,0.010251,0.015881,0.014897,0.016309,0.070709
1,Arrizabalaga,GKP,ARS,4.9,0.1,0,0,0.0,0.0,101,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Meslier,GKP,ARS,4.9,0.0,0,0,0.0,0.0,45,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Gabriel,DEF,ARS,8.0,22.7,25,1,5.0,5.0,22673,...,NFO,EVE,LIV,HUL,1.595231,1.223123,1.894836,1.777406,1.945863,8.436460
4,J.Timber,DEF,ARS,6.5,0.4,1,0,0.5,0.2,11618,...,NFO,EVE,LIV,HUL,0.055686,0.042696,0.066144,0.062045,0.067926,0.294497
5,Saliba,DEF,ARS,5.9,0.2,0,0,0.0,0.0,368,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Lewis-Skelly,MID,ARS,5.4,0.6,9,0,2.2,1.5,859,...,NFO,EVE,LIV,HUL,0.765719,0.587105,0.909531,0.853163,0.934024,4.049543
7,Calafiori,DEF,ARS,5.8,50.5,29,1,5.8,5.0,71574,...,NFO,EVE,LIV,HUL,2.268572,1.739399,2.694639,2.527642,2.767205,11.997457
8,Hincapie,DEF,ARS,5.2,0.9,2,0,1.0,0.2,1363,...,NFO,EVE,LIV,HUL,0.021319,0.016346,0.025323,0.023753,0.026005,0.112745
9,White,DEF,ARS,5.5,4.9,21,0,5.2,2.5,3213,...,NFO,EVE,LIV,HUL,1.027607,0.787905,1.220605,1.144959,1.253475,5.434552
10,Mosquera,DEF,ARS,5.3,1.6,12,0,6.0,1.5,1133,...,NFO,EVE,LIV,HUL,0.021158,0.016223,0.025132,0.023574,0.025808,0.111894
11,Saka,MID,ARS,9.5,13.6,32,2,6.4,5.8,99340,...,NFO,EVE,LIV,HUL,7.193863,5.515804,8.544964,8.015397,8.775075,38.045103
12,Rice,MID,ARS,7.4,11.7,20,1,4.0,4.2,7427,...,NFO,EVE,LIV,HUL,1.500491,1.150483,1.782303,1.671846,1.830299,7.935422
13,Eze,MID,ARS,6.2,1.0,4,1,1.0,0.8,2114,...,NFO,EVE,LIV,HUL,0.256596,0.196742,0.304788,0.285899,0.312996,1.357020
14,Ødegaard,MID,ARS,6.8,19.8,29,2,5.8,4.5,71304,...,NFO,EVE,LIV,HUL,4.128597,3.165549,4.904001,4.600080,5.036063,21.834289
15,Madueke,MID,ARS,6.2,0.2,2,0,1.0,0.2,706,...,NFO,EVE,LIV,HUL,0.252458,0.193569,0.299873,0.281289,0.307949,1.335139
16,Merino,MID,ARS,5.8,0.4,4,1,0.8,0.8,694,...,NFO,EVE,LIV,HUL,0.488895,0.374854,0.580716,0.544727,0.596354,2.585546
17,Martinelli,MID,ARS,6.3,0.1,0,0,0.0,0.0,0,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,Zubimendi,MID,ARS,5.3,0.6,5,1,1.0,1.0,473,...,NFO,EVE,LIV,HUL,0.538859,0.413164,0.640064,0.600397,0.657301,2.849785
19,Dowman,MID,ARS,5.3,0.1,1,1,1.0,0.2,438,...,NFO,EVE,LIV,HUL,0.164071,0.125799,0.194886,0.182808,0.200134,0.867698
20,Nwaneri,MID,ARS,5.4,0.0,0,0,0.0,0.0,0,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,Fábio Vieira,MID,ARS,5.5,0.0,0,0,0.0,0.0,0,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,Nelson,MID,ARS,5.5,0.0,0,0,0.0,0.0,0,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,Gyökeres,FWD,ARS,7.1,3.1,2,1,1.0,0.5,8539,...,NFO,EVE,LIV,HUL,0.351211,0.269286,0.417173,0.391319,0.428407,1.857396
24,Havertz,FWD,ARS,7.6,8.4,19,2,3.8,3.2,50026,...,NFO,EVE,LIV,HUL,3.929066,3.012561,4.666995,4.377762,4.792675,20.779059
25,G.Jesus,FWD,ARS,5.9,0.1,0,0,0.0,0.0,0,...,NFO,EVE,LIV,HUL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,Konsa,DEF,ARS,4.6,19.4,12,1,3.0,3.0,86432,...,NFO,EVE,LIV,HUL,0.446377,0.342254,0.530213,0.497353,0.544491,2.360689
27,Bruno G.,MID,ARS,6.7,1.8,9,1,3.0,2.2,5201,...,NFO,EVE,LIV,HUL,0.484263,0.371302,0.575214,0.539565,0.590704,2.561049
28,Tzolis,MID,ARS,6.3,12.2,16,2,3.2,2.5,11194,...,NFO,EVE,LIV,HUL,1.776359,1.362001,2.109982,1.979218,2.166803,9.394361
29,M.Bizot,GKP,AVL,4.5,0.1,1,0,1.0,0.0,58,...,NEW,MCI,FUL,MUN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [17]:
t.head(5)

,id,short_name,position,F1,F2,F3,F4,F5,fdr_sum_next_5,Team_ID,...,PPDA_Attacking_Passes,PPDA_Defensive_Actions,PPDA_Allowed_Att,PPDA_Allowed_Def,PPDA_Coeff,PPDA_Allowed_Coeff,Played,xgA/90,xg/90,defensive_multiplier
0,1,ARS,2,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,83,...,844,82,1313,103,10.292683,12.747573,5,1.090756,1.882608,0.666140
1,2,AVL,16,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,71,...,1241,72,1080,125,17.236111,8.640000,5,2.171269,0.997899,1.319227
2,3,BOU,17,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,73,...,1163,118,1006,117,9.855932,8.598291,5,1.398999,1.619735,0.962773
3,4,BRE,4,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,244,...,1130,125,944,122,9.040000,7.737705,5,1.499141,2.102884,1.005622
4,5,BHA,3,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,220,...,742,135,1569,70,5.496296,22.414286,5,1.725226,2.578624,1.076349

In [18]:
p.columns

Index(['web_name', 'element_type', 'team', 'now_cost', 'selected_by_percent',
       'total_points', 'event_points', 'points_per_game', 'form',
       'transfers_in_event', 'transfers_out_event', 'minutes', 'starts',
       'starts_per_90', 'goals_scored', 'assists', 'expected_goals',
       'expected_assists', 'expected_goals_per_90',
       'expected_goal_involvements_per_90', 'clean_sheets',
       'clean_sheets_per_90', 'goals_conceded', 'own_goals',
       'defensive_contribution', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'id', 'defensive_contribution_per_90',
       'expected_goals_conceded_per_90', 'expected_goals_conceded',
       'expected_goal_involvements', 'F1', 'fdr_sum_next_5',
       'goal_involvements', 'in_my_team', 'attacking_index', 'opp1', 'opp2',
       'opp3', 'opp4', 'opp5', 'opp_1_score', 'opp_2_score', 'opp_3_score',
       'opp_4_score', 'opp_5_score', '5gw_attack_score'],
      dtype='str')