In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from dataFetch import fetch_team_data, fetch_understat, clean_data

In [3]:
u = fetch_team_data()
u.head(10)

,id,short_name,position,F1,F2,F3,F4,F5,fdr_sum_next_5,Team_ID,...,Deep_Passes_Allowed,PPDA_Attacking_Passes,PPDA_Defensive_Actions,PPDA_Allowed_Att,PPDA_Allowed_Def,PPDA_Coeff,PPDA_Allowed_Coeff,Played,xgA/90,xg/90
0,1,ARS,2,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,83,...,23,844,82,1313,103,10.292683,12.747573,5,1.090756,1.882608
1,2,AVL,16,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,71,...,45,1241,72,1080,125,17.236111,8.640000,5,2.171269,0.997899
2,3,BOU,17,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,73,...,42,1163,118,1006,117,9.855932,8.598291,5,1.398999,1.619735
3,4,BRE,4,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,244,...,42,1130,125,944,122,9.040000,7.737705,5,1.499141,2.102884
4,5,BHA,3,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,220,...,39,742,135,1569,70,5.496296,22.414286,5,1.725226,2.578624
5,6,CHE,10,BOU(H) (3),EVE(A) (3),TOT(H) (2),MUN(H) (4),SUN(A) (3),15,80,...,34,1275,92,1004,100,13.858696,10.040000,5,2.059466,1.788420
6,7,COV,18,NEW(H) (3),TOT(A) (3),FUL(H) (2),SUN(H) (3),EVE(A) (3),14,294,...,38,1527,82,897,87,18.621951,10.310345,5,1.717609,0.995119
7,8,CRY,15,NFO(H) (3),BHA(A) (4),NEW(H) (3),TOT(A) (3),LIV(H) (4),17,78,...,56,1597,102,1177,107,15.656863,11.000000,5,2.003992,1.516864
8,9,EVE,7,HUL(A) (2),CHE(H) (4),ARS(A) (5),NEW(A) (3),COV(H) (2),16,72,...,35,1492,98,1075,118,15.224490,9.110169,5,1.439970,1.670814
9,10,FUL,19,IPS(A) (2),HUL(H) (2),COV(A) (2),AVL(A) (3),NEW(H) (3),12,228,...,39,1181,101,1590,96,11.693069,16.562500,5,2.085758,1.592701

In [5]:
p, t = clean_data()

KeyError: 'team'

In [ ]:
p.head(30)

,web_name,element_type,team,now_cost,selected_by_percent,total_points,event_points,points_per_game,form,transfers_in_event,...,xG_Created_temp_opp2,short_name_temp_opp3,xG_Conceded_temp_opp3,xG_Created_temp_opp3,short_name_temp_opp4,xG_Conceded_temp_opp4,xG_Created_temp_opp4,short_name_temp_opp5,xG_Conceded_temp_opp5,xG_Created_temp_opp5
0,Raya,GKP,ARS,6.1,42.2,30,1,6.0,6.0,120710,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
1,Arrizabalaga,GKP,ARS,4.9,0.1,0,0,0.0,0.0,101,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
2,Meslier,GKP,ARS,4.9,0.0,0,0,0.0,0.0,45,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
3,Gabriel,DEF,ARS,8.0,22.7,25,1,5.0,5.0,22638,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
4,J.Timber,DEF,ARS,6.5,0.4,1,0,0.5,0.2,11607,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
5,Saliba,DEF,ARS,5.9,0.2,0,0,0.0,0.0,368,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
6,Lewis-Skelly,MID,ARS,5.4,0.6,9,0,2.2,1.5,859,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
7,Calafiori,DEF,ARS,5.8,50.5,29,1,5.8,5.0,71499,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
8,Hincapie,DEF,ARS,5.2,0.9,2,0,1.0,0.2,1360,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
9,White,DEF,ARS,5.5,4.9,21,0,5.2,2.5,3213,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
10,Mosquera,DEF,ARS,5.3,1.6,12,0,6.0,1.5,1133,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
11,Saka,MID,ARS,9.5,13.6,32,2,6.4,5.8,99184,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
12,Rice,MID,ARS,7.4,11.7,20,1,4.0,4.2,7422,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
13,Eze,MID,ARS,6.2,1.0,4,1,1.0,0.8,2112,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
14,Ødegaard,MID,ARS,6.8,19.8,29,2,5.8,4.5,71232,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
15,Madueke,MID,ARS,6.2,0.2,2,0,1.0,0.2,706,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
16,Merino,MID,ARS,5.8,0.4,4,1,0.8,0.8,693,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
17,Martinelli,MID,ARS,6.3,0.1,0,0,0.0,0.0,0,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
18,Zubimendi,MID,ARS,5.3,0.6,5,1,1.0,1.0,473,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
19,Dowman,MID,ARS,5.3,0.1,1,1,1.0,0.2,438,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
20,Nwaneri,MID,ARS,5.4,0.0,0,0,0.0,0.0,0,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
21,Fábio Vieira,MID,ARS,5.5,0.0,0,0,0.0,0.0,0,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
22,Nelson,MID,ARS,5.5,0.0,0,0,0.0,0.0,0,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
23,Gyökeres,FWD,ARS,7.1,3.1,2,1,1.0,0.5,8500,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
24,Havertz,FWD,ARS,7.6,8.4,19,2,3.8,3.2,50023,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
25,G.Jesus,FWD,ARS,5.9,0.1,0,0,0.0,0.0,0,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
26,Konsa,DEF,ARS,4.6,19.4,12,1,3.0,3.0,86364,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
27,Bruno G.,MID,ARS,6.7,1.8,9,1,3.0,2.2,5189,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
28,Tzolis,MID,ARS,6.3,12.2,16,2,3.2,2.5,11186,...,8.480773,EVE,7.199851,8.35407,LIV,6.939151,8.244159,HUL,7.18528,5.730891
29,M.Bizot,GKP,AVL,4.5,0.1,1,0,1.0,0.0,58,...,5.544181,MCI,7.177241,11.04073,FUL,10.428790,7.963503,MUN,7.21596,10.585021

In [5]:
t.head(5)

,id,short_name,position,F1,F2,F3,F4,F5,fdr_sum_next_5,Team_ID,...,Deep_Passes_Allowed,PPDA_Attacking_Passes,PPDA_Defensive_Actions,PPDA_Allowed_Att,PPDA_Allowed_Def,PPDA_Coeff,PPDA_Allowed_Coeff,Played,xgA/90,xg/90
0,1,ARS,2,LEE(H) (3),NFO(A) (3),EVE(H) (3),LIV(A) (4),HUL(H) (2),15,83,...,23,844,82,1313,103,10.292683,12.747573,5,1.090756,1.882608
1,2,AVL,16,BRE(H) (3),NEW(A) (3),MCI(H) (4),FUL(H) (2),MUN(A) (4),16,71,...,45,1241,72,1080,125,17.236111,8.640000,5,2.171269,0.997899
2,3,BOU,17,CHE(A) (4),SUN(H) (3),MUN(A) (4),LEE(H) (3),IPS(A) (2),16,73,...,42,1163,118,1006,117,9.855932,8.598291,5,1.398999,1.619735
3,4,BRE,4,AVL(A) (3),LIV(H) (4),HUL(A) (2),NFO(H) (3),BHA(A) (4),16,244,...,42,1130,125,944,122,9.040000,7.737705,5,1.499141,2.102884
4,5,BHA,3,SUN(A) (3),CRY(H) (2),LIV(A) (4),MCI(A) (5),BRE(H) (3),17,220,...,39,742,135,1569,70,5.496296,22.414286,5,1.725226,2.578624

In [6]:
p.columns

Index(['web_name', 'element_type', 'team', 'now_cost', 'selected_by_percent',
       'total_points', 'event_points', 'points_per_game', 'form',
       'transfers_in_event', 'transfers_out_event', 'minutes', 'starts',
       'starts_per_90', 'goals_scored', 'assists', 'expected_goals',
       'expected_assists', 'expected_goals_per_90',
       'expected_goal_involvements_per_90', 'clean_sheets',
       'clean_sheets_per_90', 'goals_conceded', 'own_goals',
       'defensive_contribution', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'id', 'defensive_contribution_per_90',
       'expected_goals_conceded_per_90', 'expected_goals_conceded',
       'expected_goal_involvements', 'F1', 'fdr_sum_next_5',
       'goal_involvements', 'in_my_team', 'opp1', 'opp2', 'opp3', 'opp4',
       'opp5', 'short_name', 'xg/90', 'xgA/90', 'xg/90_temp_opp2',
       'xgA/90_temp_opp2', 'xg/90_temp_opp3', 'xgA/90_temp_opp3',
       'xg/90_temp_opp4', 'xgA/90_temp_opp4', 'xg/90_temp_opp5',
       'xgA/90_temp_opp5'],
      dtype='str')